# Generated by Django 3.0.3 on 2020-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_submit', models.CharField(max_length=255, verbose_name='Title')),
                ('text_submit', models.TextField(blank=True, verbose_name='Text')),
            ],
        ),
    ]
